#ifndef CCONFD_DEBUG_H
#define CCONFD_DEBUG_H

#ifdef DEBUG
#define BACKWARD_HAS_DWARF 1
#define BACKWARD_HAS_BACKTRACE_SYMBOL 0
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_DEBUG
#else
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
#endif // DEBUG

#endif